name: CI Analyze

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Reason to manually dispatch"
        required: true
        default: "Se estan realizando pruebas"
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    timeout-minutes: 16

    steps:
      - name: Checkout app
        uses: actions/checkout@v3

      - name: Setup java version
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.5"
          channel: "stable"

      - name: Getting packages
        run: flutter pub get

#      - name: Analyze
#        run: flutter analyze
#
#      - name: Run tests
#        run: flutter test --coverage

      # I will add this in the future
      # - name: Check coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v2
      #   with:
      #     path: "./coverage/lcov.info"
      #     min_coverage: 50
